export const countries = [
  { code: "us", name: "미국", initial: "ㅁㄱ", continent: "북아메리카" },
  { code: "cn", name: "중국", initial: "ㅈㄱ", continent: "아시아" },
  { code: "jp", name: "일본", initial: "ㅇㅂ", continent: "아시아" },
  { code: "de", name: "독일", initial: "ㄷㅇ", continent: "유럽" },
  { code: "in", name: "인도", initial: "ㅇㄷ", continent: "아시아" },
  { code: "gb", name: "영국", initial: "ㅇㄱ", continent: "유럽" },
  { code: "fr", name: "프랑스", initial: "ㅍㄹㅅ", continent: "유럽" },
  { code: "it", name: "이탈리아", initial: "ㅇㅌㄹㅇ", continent: "유럽" },
  { code: "ca", name: "캐나다", initial: "ㅋㄴㄷ", continent: "북아메리카" },
  { code: "ru", name: "러시아", initial: "ㄹㅅㅇ", continent: "유럽" },
  { code: "br", name: "브라질", initial: "ㅂㄹㅈ", continent: "남아메리카" },
  { code: "kr", name: "대한민국", initial: "ㄷㅎㅁㄱ", continent: "아시아" },
  { code: "au", name: "호주", initial: "ㅎㅈ", continent: "오세아니아" },
  { code: "mx", name: "멕시코", initial: "ㅁㅅㅋ", continent: "북아메리카" },
  { code: "es", name: "스페인", initial: "ㅅㅍㅇ", continent: "유럽" },
  { code: "nl", name: "네덜란드", initial: "ㄴㄷㄹㄷ", continent: "유럽" },
  { code: "ch", name: "스위스", initial: "ㅅㅇㅅ", continent: "유럽" },
  { code: "sa", name: "사우디 아라비아", initial: "ㅅㅇㄷ ㅇㄹㅂㅇ", continent: "중동" },
  { code: "tr", name: "터키", initial: "ㅌㅋ", continent: "아시아" },
  { code: "id", name: "인도네시아", initial: "ㅇㄷㄴㅅㅇ", continent: "아시아" },
  { code: "pl", name: "폴란드", initial: "ㅍㄹㄷ", continent: "유럽" },
  { code: "be", name: "벨기에", initial: "ㅂㄱㅇ", continent: "유럽" },
  { code: "se", name: "스웨덴", initial: "ㅅㅇㄷ", continent: "유럽" },
  { code: "th", name: "태국", initial: "ㅌㄱ", continent: "아시아" },
  { code: "ng", name: "나이지리아", initial: "ㄴㅇㅈㄹㅇ", continent: "아프리카" },
  { code: "ph", name: "필리핀", initial: "ㅍㄹㅍ", continent: "아시아" },
  { code: "ie", name: "아일랜드", initial: "ㅇㅇㄹㄷ", continent: "유럽" },
  { code: "no", name: "노르웨이", initial: "ㄴㄹㅇㅇ", continent: "유럽" },
  { code: "sg", name: "싱가포르", initial: "ㅅㄱㅍㄹ", continent: "아시아" },
  { code: "dk", name: "덴마크", initial: "ㄷㅁㅋ", continent: "유럽" },
  { code: "my", name: "말레이시아", initial: "ㅁㄹㅇㅅㅇ", continent: "아시아" },
  { code: "eg", name: "이집트", initial: "ㅇㅈㅌ", continent: "아프리카" },
  { code: "vn", name: "베트남", initial: "ㅂㅌㄴ", continent: "아시아" },
  { code: "hk", name: "홍콩", initial: "ㅎㅋ", continent: "아시아" },
  { code: "cz", name: "체코", initial: "ㅊㅋ", continent: "유럽" },
  { code: "pt", name: "포르투갈", initial: "ㅍㄹㅌㄱ", continent: "유럽" },
  { code: "nz", name: "뉴질랜드", initial: "ㄴㅈㄹㄷ", continent: "오세아니아" },
  { code: "gr", name: "그리스", initial: "ㄱㄹㅅ", continent: "유럽" },
  { code: "fi", name: "핀란드", initial: "ㅍㄹㄷ", continent: "유럽" },
  { code: "ro", name: "루마니아", initial: "ㄹㅁㄴㅇ", continent: "유럽" },
  { code: "ua", name: "우크라이나", initial: "ㅇㅋㄹㅇㄴ", continent: "유럽" },
  { code: "cl", name: "칠레", initial: "ㅊㄹ", continent: "남아메리카" },
  { code: "bd", name: "방글라데시", initial: "ㅂㄱㄹㄷㅅ", continent: "아시아" },
  { code: "pk", name: "파키스탄", initial: "ㅍㅋㅅㅌ", continent: "아시아" },
  { code: "ar", name: "아르헨티나", initial: "ㅇㄹㅎㅌㄴ", continent: "남아메리카" },
  { code: "ke", name: "케냐", initial: "ㅋㄴ", continent: "아프리카" },
  { code: "co", name: "콜롬비아", initial: "ㅋㄹㅂㅇ", continent: "남아메리카" },
  { code: "ae", name: "아랍에미리트", initial: "ㅇㄹㅇㅁㄹㅌ", continent: "중동" },
  { code: "ma", name: "모로코", initial: "ㅁㄹㅋ", continent: "아프리카" },
  { code: "np", name: "네팔", initial: "ㄴㅍ", continent: "아시아" },
  { code: "ec", name: "에콰도르", initial: "ㅇㅋㄷㄹ", continent: "남아메리카" },
  { code: "pe", name: "페루", initial: "ㅍㄹ", continent: "남아메리카" },
  { code: "ve", name: "베네수엘라", initial: "ㅂㄴㅅㅇㄹ", continent: "남아메리카" },
  { code: "cu", name: "쿠바", initial: "ㅋㅂ", continent: "북아메리카" },
  { code: "py", name: "파라과이", initial: "ㅍㄹㄱㅇ", continent: "남아메리카" },
  { code: "uy", name: "우루과이", initial: "ㅇㄹㄱㅇ", continent: "남아메리카" },
  { code: "bo", name: "볼리비아", initial: "ㅂㄹㅂㅇ", continent: "남아메리카" },
  { code: "do", name: "도미니카 공화국", initial: "ㄷㅁㄴㅋ ㄱㅎㄱ", continent: "북아메리카" },
  { code: "hn", name: "온두라스", initial: "ㅇㄷㄹㅅ", continent: "북아메리카" },
  { code: "sv", name: "엘살바도르", initial: "ㅇㅅㅂㄷㄹ", continent: "북아메리카" },
  { code: "cr", name: "코스타리카", initial: "ㅋㅅㅌㄹㅋ", continent: "북아메리카" },
  { code: "ni", name: "니카라과", initial: "ㄴㅋㄹㄱ", continent: "북아메리카" },
  { code: "gt", name: "과테말라", initial: "ㄱㅌㅁㄹ", continent: "북아메리카" },
  { code: "jm", name: "자메이카", initial: "ㅈㅁㅇㅋ", continent: "북아메리카" },
  { code: "bs", name: "바하마", initial: "ㅂㅎㅁ", continent: "북아메리카" },
  { code: "tt", name: "트리니다드 토바고", initial: "ㅌㄹㄴㄷㄷ ㅌㅂㄱ", continent: "북아메리카" },
  { code: "bb", name: "바베이도스", initial: "ㅂㅂㅇㄷㅅ", continent: "북아메리카" },
  { code: "bm", name: "버뮤다", initial: "ㅂㅁㄷ", continent: "북아메리카" },
  { code: "tc", name: "터크스와 케이커스", initial: "ㅌㅋㅅㅇ ㅋㅇㅋㅅ", continent: "북아메리카" },
  { code: "ky", name: "케이맨 제도", initial: "ㅋㅇㅁ ㅈㄷ", continent: "북아메리카" },
  { code: "af", name: "아프가니스탄", initial: "ㅇㅍㄱㄴㅅㅌ", continent: "아시아" },
  { code: "al", name: "알바니아", initial: "ㅇㅂㄴㅇ", continent: "유럽" },
  { code: "dz", name: "알제리", initial: "ㅇㅈㄹ", continent: "아프리카" },
  { code: "as", name: "아메리칸사모아", initial: "ㅇㅁㄹㅋㅅㅁㅇ", continent: "오세아니아" },
  { code: "ad", name: "안도라", initial: "ㅇㄷㄹ", continent: "유럽" },
  { code: "ao", name: "앙골라", initial: "ㅇㄱㄹ", continent: "아프리카" },
  { code: "ai", name: "앙길라", initial: "ㅇㄱㄹ", continent: "북아메리카" },
  { code: "ag", name: "앤티가 바부다", initial: "ㅇㅌㄱ ㅂㅂㄷ", continent: "북아메리카" },
  { code: "am", name: "아르메니아", initial: "ㅇㄹㅁㄴㅇ", continent: "아시아" },
  { code: "aw", name: "아루바", initial: "ㅇㄹㅂ", continent: "오세아니아" },
  { code: "at", name: "오스트리아", initial: "ㅇㅅㅌㄹㅇ", continent: "유럽" },
  { code: "az", name: "아제르바이잔", initial: "ㅇㅈㄹㅂㅇㅈ", continent: "중동" },
  { code: "bh", name: "바레인", initial: "ㅂㄹㅇ", continent: "중동" },
  { code: "by", name: "벨라루스", initial: "ㅂㄹㄹㅅ", continent: "유럽" },
  { code: "bz", name: "벨리즈", initial: "ㅂㄹㅈ", continent: "북아메리카" },
  { code: "bj", name: "베냉", initial: "ㅂㄴ", continent: "아프리카" },
  { code: "bt", name: "부탄", initial: "ㅂㅌ", continent: "아시아" },
  { code: "ba", name: "보스니아 헤르체고비나", initial: "ㅂㅅㄴㅇ ㅎㄹㅊㄱㅂㄴ", continent: "유럽" },
  { code: "bw", name: "보츠와나", initial: "ㅂㅊㅇㄴ", continent: "아프리카" },
  { code: "bn", name: "브루나이", initial: "ㅂㄹㄴㅇ", continent: "아시아" },
  { code: "bg", name: "불가리아", initial: "ㅂㄱㄹㅇ", continent: "유럽" },
  { code: "bf", name: "부르키나파소", initial: "ㅂㄹㅋㄴㅍㅅ", continent: "아프리카" },
  { code: "bi", name: "부룬디", initial: "ㅂㄹㄷ", continent: "아프리카" },
  { code: "kh", name: "캄보디아", initial: "ㅋㅂㄷㅇ", continent: "아시아" },
  { code: "cm", name: "카메룬", initial: "ㅋㅁㄹ", continent: "아프리카" },
  { code: "cv", name: "카보베르데", initial: "ㅋㅂㅂㄹㄷ", continent: "아프리카" },
  { code: "cf", name: "중앙아프리카 공화국", initial: "ㅈㅇㅇㅍㄹㅋ ㄱㅎㄱ", continent: "아프리카" },
  { code: "td", name: "차드", initial: "ㅊㄷ", continent: "아프리카" },
  { code: "km", name: "코모로", initial: "ㅋㅁㄹ", continent: "아프리카" },
  { code: "cg", name: "콩고", initial: "ㅋㄱ", continent: "아프리카" },
  { code: "cd", name: "콩고 민주 공화국", initial: "ㅋㄱ ㅁㅈ ㄱㅎㄱ", continent: "아프리카" },
  { code: "hr", name: "크로아티아", initial: "ㅋㄹㅇㅌㅇ", continent: "유럽" },
  { code: "cy", name: "키프로스", initial: "ㅋㅍㄹㅅ", continent: "유럽" },
  { code: "dj", name: "지부티", initial: "ㅈㅂㅌ", continent: "아프리카" },
  { code: "dm", name: "도미니카 연방", initial: "ㄷㅁㄴㅋ ㅇㅂ", continent: "북아메리카" },
  { code: "gq", name: "적도 기니", initial: "ㅈㄷ ㄱㄴ", continent: "아프리카" },
  { code: "er", name: "에리트레아", initial: "ㅇㄹㅌㄹㅇ", continent: "아프리카" },
  { code: "ee", name: "에스토니아", initial: "ㅇㅅㅌㄴㅇ", continent: "유럽" },
  { code: "et", name: "에티오피아", initial: "ㅇㅌㅇㅍㅇ", continent: "아프리카" },
  { code: "fj", name: "피지", initial: "ㅍㅈ", continent: "오세아니아" },
  { code: "ga", name: "가봉", initial: "ㄱㅂ", continent: "아프리카" },
  { code: "gm", name: "감비아", initial: "ㄱㅂㅇ", continent: "아프리카" },
  { code: "ge", name: "조지아", initial: "ㅈㅈㅇ", continent: "아시아" },
  { code: "gh", name: "가나", initial: "ㄱㄴ", continent: "아프리카" },
  { code: "gn", name: "기니", initial: "ㄱㄴ", continent: "아프리카" },
  { code: "gw", name: "기니비사우", initial: "ㄱㄴㅂㅅㅇ", continent: "아프리카" },
  { code: "gy", name: "가이아나", initial: "ㄱㅇㅇㄴ", continent: "남아메리카" },
  { code: "ht", name: "아이티", initial: "ㅇㅇㅌ", continent: "북아메리카" },
  { code: "hu", name: "헝가리", initial: "ㅎㄱㄹ", continent: "유럽" },
  { code: "is", name: "아이슬란드", initial: "ㅇㅇㅅㄹㄷ", continent: "유럽" },
  { code: "ir", name: "이란", initial: "ㅇㄹ", continent: "중동" },
  { code: "iq", name: "이라크", initial: "ㅇㄹㅋ", continent: "중동" },
  { code: "ax", name: "올란드 제도", initial: "ㅇㄹㄷ ㅈㄷ", continent: "유럽" },
  { code: "aq", name: "남극", initial: "ㄴㄱ", continent: "남극 대륙" },
  { code: "bv", name: "부베섬", initial: "ㅂㅂㅅ", continent: "남극 대륙" },
  { code: "cc", name: "코코스킬링 제도", initial: "ㅋㅋㅅㅋㄹ ㅈㄷ", continent: "오세아니아" },
  { code: "ck", name: "쿡 제도", initial: "ㅋ ㅈㄷ", continent: "오세아니아" },
  { code: "cx", name: "크리스마스섬", initial: "ㅋㄹㅅㅁㅅㅅ", continent: "오세아니아" },
  { code: "eh", name: "서사하라", initial: "ㅅㅅㅎㄹ", continent: "아프리카" },
  { code: "fk", name: "포클랜드 제도말비나스", initial: "ㅍㅋㄹㄷ ㅈㄷㅁㅂㄴㅅ", continent: "남아메리카" },
  { code: "fo", name: "페로 제도", initial: "ㅍㄹ ㅈㄷ", continent: "유럽" },
  { code: "gf", name: "프랑스령 기아나", initial: "ㅍㄹㅅㄹ ㄱㅇㄴ", continent: "남아메리카" },
  { code: "gg", name: "건지", initial: "ㄱㅈ", continent: "유럽" },
  { code: "gi", name: "지브롤터", initial: "ㅈㅂㄹㅌ", continent: "유럽" },
  { code: "gl", name: "그린란드", initial: "ㄱㄹㄹㄷ", continent: "북아메리카" },
  { code: "gp", name: "과들루프", initial: "ㄱㄷㄹㅍ", continent: "북아메리카" },
  { code: "gs", name: "사우스조지아 사우스샌드위치 제도", initial: "ㅅㅇㅅㅈㅈㅇ ㅅㅇㅅㅅㄷㅇㅊ ㅈㄷ", continent: "남극 대륙" },
  { code: "gu", name: "괌", initial: "ㄱ", continent: "오세아니아" },
  { code: "hm", name: "허드 맥도널드 제도", initial: "ㅎㄷ ㅁㄷㄴㄷ ㅈㄷ", continent: "남극 대륙" },
  { code: "im", name: "맨섬", initial: "ㅁㅅ", continent: "유럽" },
  { code: "io", name: "영국령 인도양 지역", initial: "ㅇㄱㄹ ㅇㅇㅇ ㅈㅇ", continent: "아시아" },
  { code: "je", name: "저지", initial: "ㅈㅈ", continent: "유럽" },
  { code: "ki", name: "키리바시", initial: "ㅋㄹㅂㅅ", continent: "오세아니아" },
  { code: "kn", name: "세인트키츠 네비스", initial: "ㅅㅇㅌㅋㅊ ㄴㅂㅅ", continent: "북아메리카" },
  { code: "lc", name: "세인트루시아", initial: "ㅅㅇㅌㄹㅅㅇ", continent: "북아메리카" },
  { code: "mh", name: "마셜 제도", initial: "ㅁㅅ ㅈㄷ", continent: "오세아니아" },
  { code: "mp", name: "북마리아나 제도", initial: "ㅂㅁㄹㅇㄴㅈㄷ", continent: "오세아니아" },
  { code: "mq", name: "마르티니크", initial: "ㅁㄹㅌㄴㅋ", continent: "북아메리카" },
  { code: "ms", name: "몬트세랫", initial: "ㅁㅌㅅㄹ", continent: "북아메리카" },
  { code: "nc", name: "뉴칼레도니아", initial: "ㄴㅋㄹㄷㄴㅇ", continent: "오세아니아" },
  { code: "nf", name: "노퍽섬", initial: "ㄴㅍㅅ", continent: "오세아니아" },
  { code: "nu", name: "니우에", initial: "ㄴㅇㅇ", continent: "오세아니아" },
  { code: "om", name: "오만", initial: "ㅇㅁ", continent: "중동" },
  { code: "pa", name: "파나마", initial: "ㅍㄴㅁ", continent: "북아메리카" },
  { code: "pf", name: "프랑스령 폴리네시아", initial: "ㅍㄹㅅㄹ ㅍㄹㄴㅅㅇ", continent: "오세아니아" },
  { code: "pg", name: "파푸아뉴기니", initial: "ㅍㅍㅇㄴㄱㄴ", continent: "오세아니아" },
  { code: "pm", name: "생피에르 미클롱", initial: "ㅅㅍㅇㄹ ㅁㅋㄹ", continent: "북아메리카" },
  { code: "pn", name: "핏케언 제도", initial: "ㅍㅋㅇ ㅈㄷ", continent: "오세아니아" },
  { code: "pr", name: "푸에르토리코", initial: "ㅍㅇㄹㅌㄹㅋ", continent: "북아메리카" },
  { code: "ps", name: "팔레스타인", initial: "ㅍㄹㅅㅌㅇ", continent: "중동" },
  { code: "pw", name: "팔라우", initial: "ㅍㄹㅇ", continent: "오세아니아" },
  { code: "qa", name: "카타르", initial: "ㅋㅌㄹ", continent: "중동" },
  { code: "re", name: "레위니옹", initial: "ㄹㅇㄴㅇ", continent: "아프리카" },
  { code: "rw", name: "르완다", initial: "ㄹㅇㄷ", continent: "아프리카" },
  { code: "sb", name: "솔로몬 제도", initial: "ㅅㄹㅁ ㅈㄷ", continent: "오세아니아" },
  { code: "sc", name: "세이셸", initial: "ㅅㅇㅅ", continent: "아프리카" },
  { code: "sd", name: "수단", initial: "ㅅㄷ", continent: "아프리카" },
  { code: "sh", name: "세인트헬레나", initial: "ㅅㅇㅌㅎㄹㄴ", continent: "아프리카" },
  { code: "sj", name: "스발바르 얀마옌", initial: "ㅅㅂㅂㄹ ㅇㅁㅇ", continent: "유럽" },
  { code: "sk", name: "슬로바키아", initial: "ㅅㄹㅂㅋㅇ", continent: "유럽" },
  { code: "sl", name: "시에라리온", initial: "ㅅㅇㄹㄹㅇ", continent: "아프리카" },
  { code: "sm", name: "산마리노", initial: "ㅅㅁㄹㄴ", continent: "유럽" },
  { code: "sn", name: "세네갈", initial: "ㅅㄴㄱ", continent: "아프리카" },
  { code: "so", name: "소말리아", initial: "ㅅㅁㄹㅇ", continent: "아프리카" },
  { code: "sr", name: "수리남", initial: "ㅅㄹㄴ", continent: "남아메리카" },
  { code: "ss", name: "남수단", initial: "ㄴㅅㄷ", continent: "아프리카" },
  { code: "st", name: "상투메 프린시페", initial: "ㅅㅌㅁ ㅍㄹㅅㅍ", continent: "아프리카" },
  { code: "sx", name: "신트마르턴 네덜란드령", initial: "ㅅㅌㅁㄹㅌ ㄴㄷㄹㄷㄹ", continent: "북아메리카" },
  { code: "sy", name: "시리아", initial: "ㅅㄹㅇ", continent: "중동" },
  { code: "sz", name: "에스와티니", initial: "ㅇㅅㅇㅌㄴ", continent: "아프리카" },
  { code: "tf", name: "프랑스령 남부와 남극 지역", initial: "ㅍㄹㅅㄹ ㄴㅂㅇ ㄴㄱ ㅈㅇ", continent: "남극 대륙" },
  { code: "tg", name: "토고", initial: "ㅌㄱ", continent: "아프리카" },
  { code: "tj", name: "타지키스탄", initial: "ㅌㅈㅋㅅㅌ", continent: "아시아" },
  { code: "tk", name: "토켈라우", initial: "ㅌㅋㄹㅇ", continent: "오세아니아" },
  { code: "tl", name: "동티모르", initial: "ㄷㅌㅁㄹ", continent: "아시아" },
  { code: "tm", name: "투르크메니스탄", initial: "ㅌㄹㅋㅁㄴㅅㅌ", continent: "아시아" },
  { code: "tn", name: "튀니지", initial: "ㅌㄴㅈ", continent: "아프리카" },
  { code: "to", name: "통가", initial: "ㅌㄱ", continent: "오세아니아" },
  { code: "tv", name: "투발루", initial: "ㅌㅂㄹ", continent: "오세아니아" },
  { code: "tz", name: "탄자니아", initial: "ㅌㅈㄴㅇ", continent: "아프리카" },
  { code: "ug", name: "우간다", initial: "ㅇㄱㄷ", continent: "아프리카" },
  { code: "uz", name: "우즈베키스탄", initial: "ㅇㅈㅂㅋㅅㅌ", continent: "아시아" },
  { code: "va", name: "바티칸 시국", initial: "ㅂㅌㅋ ㅅㄱ", continent: "유럽" },
  { code: "vc", name: "세인트빈센트 그레나딘", initial: "ㅅㅇㅌㅂㅅㅌ ㄱㄹㄴㄷ", continent: "북아메리카" },
  { code: "vg", name: "영국령 버진아일랜드", initial: "ㅇㄱㄹ ㅂㅈㅇㅇㄹㄷ", continent: "북아메리카" },
  { code: "vi", name: "미국령 버진아일랜드", initial: "ㅁㄱㄹ ㅂㅈㅇㅇㄹㄷ", continent: "북아메리카" },
  { code: "vu", name: "바누아투", initial: "ㅂㄴㅇㅌ", continent: "오세아니아" },
  { code: "wf", name: "월리스 푸투나", initial: "ㅇㄹㅅ ㅍㅌㄴ", continent: "오세아니아" },
  { code: "ws", name: "사모아", initial: "ㅅㅁㅇ", continent: "오세아니아" },
  { code: "ye", name: "예멘", initial: "ㅇㅁ", continent: "중동" },
  { code: "yt", name: "마요트", initial: "ㅁㅇㅌ", continent: "아프리카" },
  { code: "zm", name: "잠비아", initial: "ㅈㅂㅇ", continent: "아프리카" },
  { code: "zw", name: "짐바브웨", initial: "ㅈㅂㅂㅇ", continent: "아프리카" },
  { code: "bl", name: "생바르텔레미", initial: "ㅅㅂㄹㅌㄹㅁ", continent: "북아메리카" },
  { code: "bq", name: "보네르섬", initial: "ㅂㄴㄹㅅ", continent: "북아메리카" },
  { code: "cw", name: "퀴라소", initial: "ㅋㄹㅅ", continent: "북아메리카" },
  { code: "ci", name: "코트디부아르", initial: "ㅋㅌㄷㅂㅇㄹ", continent: "아프리카" },
  { code: "fm", name: "미크로네시아", initial: "ㅁㅋㄹㄴㅅㅇ", continent: "오세아니아" },
  { code: "gd", name: "그레나다", initial: "ㄱㄹㄴㄷ", continent: "북아메리카" },
  { code: "il", name: "이스라엘", initial: "ㅇㅅㄹㅇ", continent: "중동" },
  { code: "jo", name: "요르단", initial: "ㅇㄹㄷ", continent: "중동" },
  { code: "kg", name: "키르기스스탄", initial: "ㅋㄹㄱㅅㅌ", continent: "아시아" },
  { code: "kp", name: "북한", initial: "ㅂㅎ", continent: "아시아" },
  { code: "kw", name: "쿠웨이트", initial: "ㅋㅇㅇㅌ", continent: "중동" },
  { code: "kz", name: "카자흐스탄", initial: "ㅋㅈㅎㅅㅌ", continent: "아시아" },
  { code: "la", name: "라오스", initial: "ㄹㅇㅅ", continent: "아시아" },
  { code: "lb", name: "레바논", initial: "ㄹㅂㄴ", continent: "중동" },
  { code: "li", name: "리히텐슈타인", initial: "ㄹㅎㅌㅅㅌㅇ", continent: "유럽" },
  { code: "lk", name: "스리랑카", initial: "ㅅㄹㄹㅋ", continent: "아시아" },
  { code: "lr", name: "라이베리아", initial: "ㄹㅇㅂㄹㅇ", continent: "아프리카" },
  { code: "ls", name: "레소토", initial: "ㄹㅅㅌ", continent: "아프리카" },
  { code: "lt", name: "리투아니아", initial: "ㄹㅌㅇㄴㅇ", continent: "유럽" },
  { code: "lu", name: "룩셈부르크", initial: "ㄹㅅㅂㄹㅋ", continent: "유럽" },
  { code: "lv", name: "라트비아", initial: "ㄹㅌㅂㅇ", continent: "유럽" },
  { code: "ly", name: "리비아", initial: "ㄹㅂㅇ", continent: "아프리카" },
  { code: "mc", name: "모나코", initial: "ㅁㄴㅋ", continent: "유럽" },
  { code: "md", name: "몰도바", initial: "ㅁㄷㅂ", continent: "유럽" },
  { code: "me", name: "몬테네그로", initial: "ㅁㅌㄴㄱㄹ", continent: "유럽" },
  { code: "mg", name: "마다가스카르", initial: "ㅁㄷㄱㅅㅋㄹ", continent: "아프리카" },
  { code: "mk", name: "북마케도니아", initial: "ㅂㅁㅋㄷㄴㅇ", continent: "유럽" },
  { code: "ml", name: "말리", initial: "ㅁㄹ", continent: "아프리카" },
  { code: "mm", name: "미얀마", initial: "ㅁㅇㅁ", continent: "아시아" },
  { code: "mn", name: "몽골", initial: "ㅁㄱ", continent: "아시아" },
  { code: "mo", name: "마카오", initial: "ㅁㅋㅇ", continent: "아시아" },
  { code: "mr", name: "모리타니", initial: "ㅁㄹㅌㄴ", continent: "아프리카" },
  { code: "mt", name: "몰타", initial: "ㅁㅌ", continent: "유럽" },
  { code: "mu", name: "모리셔스", initial: "ㅁㄹㅅㅅ", continent: "아프리카" },
  { code: "mv", name: "몰디브", initial: "ㅁㄷㅂ", continent: "아시아" },
  { code: "mw", name: "말라위", initial: "ㅁㄹㅇ", continent: "아프리카" },
  { code: "mz", name: "모잠비크", initial: "ㅁㅈㅂㅋ", continent: "아프리카" },
  { code: "na", name: "나미비아", initial: "ㄴㅁㅂㅇ", continent: "아프리카" },
  { code: "ne", name: "니제르", initial: "ㄴㅈㄹ", continent: "아프리카" },
  { code: "nr", name: "나우루", initial: "ㄴㅇㄹ", continent: "오세아니아" },
  { code: "rs", name: "세르비아", initial: "ㅅㄹㅂㅇ", continent: "유럽" },
  { code: "si", name: "슬로베니아", initial: "ㅅㄹㅂㄴㅇ", continent: "유럽" },
  { code: "tw", name: "대만", initial: "ㄷㅁ", continent: "아시아" },
  { code: "za", name: "남아프리카공화국", initial: "ㄴㅇㅍㄹㅋㄱㅎㄱ", continent: "아프리카" },
  { code: "xk", name: "코소보", initial: "ㅋㅅㅂ", continent: "유럽" },
];
